name: 'Setup Build Environment'
description: 'Clones dependencies and exports mkbootimg/avbtool paths'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update && sudo apt-get install -y ccache
        mkdir -p "${{ github.workspace }}/kernel"
        mkdir -p "${{ github.workspace }}/git-repo"
        curl -L https://storage.googleapis.com/git-repo-downloads/repo -o "${{ github.workspace }}/git-repo/repo"
        chmod +x "${{ github.workspace }}/git-repo/repo"
        echo "${{ github.workspace }}/git-repo" >> "$GITHUB_PATH"

        if [ -d "${{ github.workspace }}/kernel_patches" ]; then rm -rf "${{ github.workspace }}/kernel_patches"; fi
        git clone https://github.com/WildKernels/kernel_patches.git "${{ github.workspace }}/kernel_patches"

        if [ -d "${{ github.workspace }}/AnyKernel3" ]; then rm -rf "${{ github.workspace }}/AnyKernel3"; fi
        git clone https://github.com/WildKernels/AnyKernel3.git -b gki-2.0 "${{ github.workspace }}/AnyKernel3"
        
